### ISSUE TITLE
Problem with absolute path

### ISSUE THREAD

**Issue by LonFas** [Lallassu/bintris#4]
When i try to run game from linux by `go run .` i receive error with absolute path

I think it's that commit `c0d19f075a877e0c6da396358002f1fca037d0dc`

```txt
go run .
go: golang.org/x/mobile@v0.0.0-20211207041440-4e6c2922fdee (replaced by /home/nergal/go/src/golang.org/x/mobile): reading /home/nergal/go/src/golang.org/x/mobile/go.mod: open /home/nergal/go/src/golang.org/x/mobile/go.mod: no such file or directory
go: golang.org/x/mobile@v0.0.0-20211207041440-4e6c2922fdee (replaced by /home/nergal/go/src/golang.org/x/mobile): reading /home/nergal/go/src/golang.org/x/mobile/go.mod: open /home/nergal/go/src/golang.org/x/mobile/go.mod: no such file or directory
```

**Comment by LonFas** [comment]
Fixed by commented row `//replace golang.org/x/mobile => /home/nergal/go/src/golang.org/x/mobile` in go.mod and runnin `go mod tidy`. After that - `go run .` worked correctly

**Comment by Lallassu** [comment]
Yes, that is due to this:
https://github.com/Lallassu/bintris/blob/main/go.mod#L10

The reason to have that is for me to build AAB for play store. If you just want to run locally, remove that line and it should drag down the gomobile from source and not use local.

**Comment by Lallassu** [comment]
> Fixed by commented row `//replace golang.org/x/mobile => /home/nergal/go/src/golang.org/x/mobile` in go.mod and runnin `go mod tidy`. After that - `go run .` worked correctly

Exactly. And I will keep it this way as I build for Play Store with my modified `gomobile` version that can compile correctly with NDK + OpenAL :)

**Comment by LonFas** [comment]
I think this should be added to the launch instructions under linux in README.md.

similar like this

` To just run the game on Linux, just issue the command:
 ```bash
+sed '/nergal/d' go.mod
 go run .
 ````

**Comment by Lallassu** [comment]
Good point, I'll add that. Thanks
